version: '3.7'

services:
  reverse-proxy:
    image: traefik:v2.1
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - cloudflare.env
    volumes:
      - ./traefik.toml:/traefik.toml
      - /var/run/docker.sock:/var/run/docker.sock

  api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - db.env
    labels:
      - traefik.http.routers.api.rule=Host(`api.desafio.online`)
      - traefik.http.routers.api.tls=true
      - traefik.http.routers.api.certresolver=myresolver