[providers.docker]
  endpoint = "unix:///var/run/docker.sock"

[entryPoints]
  [entryPoints.web]
    address = ":80"

  [entryPoints.websecure]
    address = ":443"

[certificatesResolvers.myresolver.acme]
  email = "your@email.com"
  storage = "acme.json"

  [certificatesResolvers.myresolver.acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 0